### ISSUE TITLE
support to laravel 5.4

### ISSUE THREAD

**Issue by mikE83** [artisaninweb/laravel-soap#101]
I try to install this wrapper on laravel 5.4 thats not possible???

**Comment by artisaninweb** [comment]
It should work just fine.
Are you getting a error?

**Comment by mikE83** [comment]
i'm a begginer in laravel in your installation manual, the sintaxis is different in laravel 5.4 (Service Provider and facades) which is the correct to configure that in laravel 5.4

**Comment by simplyrupin** [comment]
Hey,
This does work on 5.4

under 'providers', add:

        `Artisaninweb\SoapWrapper\ServiceProvider::class,`

under 'aliases', add: 

      ` 'SoapWrapper' => Artisaninweb\SoapWrapper\Facade\SoapWrapper::class,`

**Comment by artisaninweb** [comment]
@simplyrupin thanks for the help.
@mikE83 did you get it to work in L5.4?

**Comment by vanessasoutoc** [comment]
I have error 
  [Symfony\Component\Debug\Exception\FatalThrowableError]     
  Class 'Artisaninweb\SoapWrapper\ServiceProvider' not found  

help me

**Comment by simplyrupin** [comment]
Try running : `composer dump-autoload`
Let me know how it goes.

Best,
Rupin

**Comment by vanessasoutoc** [comment]
Thanks @simplyrupin but error continue in run $ php artisan serve

 [Symfony\Component\Debug\Exception\FatalThrowableError]     
  Class 'Artisaninweb\SoapWrapper\ServiceProvider' not found

**Comment by simplyrupin** [comment]
Did you run a `composer install` before artisan serve? 
From the error, it seems that the package is not yet installed on your project

**Comment by vanessasoutoc** [comment]
Run $ composer install but not install de package.
Run $ composer update and install de packege.
It's work for me. Thanks
