### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by shrenik9** [artisaninweb/laravel-soap#102]
Hello , I am Getting This issue. Please Help.
Below my function
public function demo()
    {
// Add a new service to the wrapper
        $this->soapWrapper->add('getLocation',function ($service) {
            $service
                ->wsdl('https://locationtracker.vodafone.in/VLTAPI_BULK/MSISDN/')
                ->trace(true)
                ->header('wsse','UsernameToken',array("Username" => "************",
                    "Password" => "**********"),true)
                ->cache(WSDL_CACHE_NONE);

        });
        $response = $this->soapWrapper->call('getLocation.getLocation', [
            'address' => '*********'
        ]);

        var_dump($response); die;
    }

![screenshot 1](https://cloud.githubusercontent.com/assets/16605433/25430371/02aa9d1c-2a9a-11e7-84d6-5117ffc4f48a.png)

**Comment by artisaninweb** [comment]
You need a custom header for wsse security.
Here is a example on how to do so: 
http://stackoverflow.com/questions/22361180/create-wsse-auth-soap-call-for-webservices-api-in-php-using-soapclient

Hope you can figure it out.

**Comment by alireza-nazari** [comment]
> 
> 
> You need a custom header for wsse security.
> Here is a example on how to do so:
> http://stackoverflow.com/questions/22361180/create-wsse-auth-soap-call-for-webservices-api-in-php-using-soapclient
> 
> Hope you can figure it out.

Same issue here, so can you please give me some example how to use custom header with WSSE security issue?
