### ISSUE TITLE
Mistake in the Facade

### ISSUE THREAD

**Issue by lordemanonsr** [artisaninweb/laravel-soap#103]
The ServiceProvider sets up the bind in the IOC using the class reflection name. Therefore in the Facade function you need to reference it that way as well.  

Currently it is as follows:

```php
protected static function getFacadeAccessor()
  {
    return 'SoapWrapper';
  }
```
Needs to be changed to this:

```php
protected static function getFacadeAccessor()
  {
    return SoapWrapper::class;
  }
```

**Comment by artisaninweb** [comment]
Thank you, will change this asap.
