### ISSUE TITLE
ErrorException in SoapWrapper.php line 133: Undefined offset: 1

### ISSUE THREAD

**Issue by kastony** [artisaninweb/laravel-soap#104]
Hello,
I'm getting this error when trying to get response from this webservice:

       $this->soapWrapper->add('checkVat', function ($service){
            $service->wsdl('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
                    ->trace(true);
        });

        $data = [
            'countryCode' => 'EL', 
            'vatNumber'   => \Request::input('afm'),
        ];

        $response = $this->soapWrapper->call('checkVat', $data);

        var_dump($response);
       
        exit;

I also tryied 

      $response = $this->soapWrapper->call('checkVat.checkVat', $data);

and in get an  SoapFault in Client.php line 189: INVALID_INPUT error

Please can you help me.

Thanks in advance

**Comment by artisaninweb** [comment]
I'm not sure what's going on here.
Did you manage to fix the problem?

**Comment by artisaninweb** [comment]
Closing issue for now, please re-open if issue still exists.

**Comment by verner-lall** [comment]
Had the same problem, I got it working like this:
`
$soapWrapper->add('checkVatService', function ($service) {
            $service
                ->wsdl('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
                ->trace(true);
        });
        $response = $soapWrapper->call('checkVatService.checkVat', [
            'body' => [
                'countryCode'          => 'EE',
                'vatNumber'            => '12341234'
            ]
        ]
}

`

**Comment by verner-lall** [comment]
Had the same issue, got it fixed like this:
```
        $soapWrapper->add('checkVatService', function ($service) {
            $service
                ->wsdl('http://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl')
                ->trace(true);
        });
        $response = $soapWrapper->call('checkVatService.checkVat', [
            'body' => [
                'countryCode'          => 'EE',
                'vatNumber'            => '123123123'
            ]
        ]);
```
