### ISSUE TITLE
Changing SOAP Version to 1.1

### ISSUE THREAD

**Issue by simplyrupin** [artisaninweb/laravel-soap#105]
Hi Michael,
So the example you gave with the CurrencyConverter works perfectly. I have a client that uses Soap 1.1. And I'm getting the below error:

```
SoapFault in Client.php line 189:
Cannot process the message because the content type 'text/xml; charset=utf-8' was not the expected type 'application/soap+xml; charset=utf-8'.
```

I tried adding headers and custom headers with 'Content-Type : application/soap+xml; charset=utf-8'. However, that doesn't seem to work. The same error still persists.

Can I change the SOAP version by setting some parameter in soapWrapper?

**Comment by artisaninweb** [comment]
Try adding this to your option:

```
$this->soapWrapper->add('Currency', function ($service) {
    $service
        ->options([
            'soap_version' => SOAP_1_1,
        ]);
});
```

Let me know if this works out for you.
