### ISSUE TITLE
Always return String empty ('')

### ISSUE THREAD

**Issue by aUbilla** [artisaninweb/laravel-soap#106]
I have installed on my projec in laravel 4.2, but when I tried to call a any function always return an empty string:

object(stdClass)[511]
  public 'GetCultureInfoResult' => string '' (length=0).

This is my code,

`$this->soapWrapper->add('Currency', function ($service) {
      $service
            ->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL')
            ->trace(true);
});

$data = [
      'Currency' => 'USD',
];

$response = $this->soapWrapper->call('Currency.GetCultureInfo', $data);

var_dump($response);`

And the response is this: 

`public 'GetCultureInfoResult' => string '' (length=0).`

This happens with any call to any method.

**Comment by artisaninweb** [comment]
Can you post your code here please?

**Comment by artisaninweb** [comment]
Looks like `GetCultureInfo` just returns a empty string.
Did you test other functies?

**Comment by aUbilla** [comment]
Yes, always return empty string, and yes, I tested other function like "GetConversionAmount" and it's the same response :(, but I tested with SoapUI and works.

**Comment by Payalba** [comment]
I think the $data had to be send in an array.
[$data]
