### ISSUE TITLE
How to set content type to 'application/soap+xml; charset=utf-8'.

### ISSUE THREAD

**Issue by Naveen95** [artisaninweb/laravel-soap#108]
When i try to send a request to the WSDL i got this error **Cannot process the message because the content type 'text/xml; charset=utf-8' was not the expected type 'application/soap+xml; charset=utf-8'.** 

Below is my code. Now how do i set the content type

```
 public function test(){

  	$this->soapWrapper->add('bsedemo', function ($service) {
      $service
        ->wsdl('http://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc?singleWsdl')
        ->trace(true);
        
    });

  	$response = $this->soapWrapper->call('bsedemo.getPassword', [
      
      'UserId'   => '12456', 
      'Password' => '123456',
      'PassKey' => '1245601',
    ]);

  	echo "The response is: ";
    var_dump($response);

  	
  }
```

**Comment by artisaninweb** [comment]
Never seen this issue before, there is more information about this here: https://stackoverflow.com/questions/5405874/content-type-text-xml-charset-utf-8-was-not-the-expected-type-application-so

Hope you can figure it out.
Try adding a custom header or a encoding option.

**Comment by Naveen95** [comment]
is there any way to manually set the header with the request with the help of your package ?

**Comment by artisaninweb** [comment]
There is a header() function.
See: https://github.com/artisaninweb/laravel-soap#service-functions

**Comment by Naveen95** [comment]
Tried setting with header(). But still didn't work 

```
  	$this->soapWrapper->add('bsedemo', function ($service) {
      $service
        ->wsdl('http://bsestarmfdemo.bseindia.com/MFOrderEntry/MFOrder.svc?singleWsdl')
        ->trace(true)
        ->header('Content-type','application/soap+xml; charset=utf-8');
        
    });
```

Any clues ?

**Comment by mohamedrasvi** [comment]
Hi I get same error have you found the solution ? @Naveen95 @artisaninweb

**Comment by anweshan007** [comment]
Hi
I am also getting the same error. Please share the solution if you have.

**Comment by thrazu** [comment]
+1

**Comment by FlaviaRochaHF** [comment]
Hi,
Please, anyone there already got a solution? I got the very same error.
Peace.

**Comment by ashiqdey** [comment]
@Naveen95 we need your help in implementing BSE Star MF api. can you guide us? (We will pay for that)

**Comment by Vinayak-carmel** [comment]
Even am having the same problem please help us to solve it..

**Comment by Frank-Ramirez** [comment]
Hola, en mi caso se soluciono cambiando la version de SOAP de 1.2 a 1.1, el problema es que la cabecera del contenido cambia entre versiones y por eso se recibe el error de tipo de contneido; revisando el wsdl encontre que se debe usar una version anterior

Etiquetas que debe revisar: 
<wsdl:binding>
   <binding xmlns="http://schemas.xmlsoap.org/wsdl/soap/">    -----> aqui indica la version de soap que se usa, en la version 1.1 
para la version 1.2 es: http://schemas.xmlsoap.org/wsdl/soap12/
y las etiquetas cambian a: <soap12:binding>, <soap12:operation>
