### ISSUE TITLE
How to set SOAP version ?

### ISSUE THREAD

**Issue by Naveen95** [artisaninweb/laravel-soap#109]
My WSDL uses SOAP version 1.2. So there is a mismatch is communication which throws the error **Cannot process the message because the content type 'text/xml; charset=utf-8' was not the expected type 'application/soap+xml; charset=utf-8'.**. Looks like Laravel-soap uses SOAP 1.1. How do i upgrade it to SOAP 1.2 ?

**Comment by artisaninweb** [comment]
Just add a option `'soap_version' => SOAP_1_2` to your services.
