### ISSUE TITLE
Header Authentication

### ISSUE THREAD

**Issue by nimeshc64** [artisaninweb/laravel-soap#110]
```
<soap:Header>
	<sel:SecurityInfo>
		<!--Optional:-->
		<sel:UserID>'.$serviceUser.'</sel:UserID>
		<!--Optional:-->
		<sel:Password>'.$servicePSW.'</sel:Password>
	</sel:SecurityInfo>
</soap:Header>
```
i want to use this header authentication in laravel-soap how to do it ??

**Comment by artisaninweb** [comment]
You need a custom header for that.
Here is an example of wsse: https://stackoverflow.com/questions/22361180/create-wsse-auth-soap-call-for-webservices-api-in-php-using-soapclient

Please search the closed issue's there are more examples on how to do so.
