### ISSUE TITLE
Undefined offset: 1

### ISSUE THREAD

**Issue by pakincpp** [artisaninweb/laravel-soap#111]
Hello, you could help me, I have an error when trying to make a function, I have this code:
$params = ['param1' => 'value_1'];

$this->soapWrapper->add('FUNCTION_NAME', function ($service) use ($wsdl) {
			    $service
			        ->wsdl($wsdl)
			        ->trace(true)
			        ->cache(WSDL_CACHE_NONE)
			        ->options(['login' => 'login','password' => 'password']);
			});

			$response = $this->soapWrapper->call('FUNCTION_NAME', $params);

the error is: Undefined offset: 1

**Comment by artisaninweb** [comment]
Try: 

```php
$params = ['param1' => 'value_1'];

$this->soapWrapper->add('SERVICE_NAME', function ($service) use ($wsdl) {
$service
->wsdl($wsdl)
->trace(true)
->cache(WSDL_CACHE_NONE)
->options(['login' => 'login','password' => 'password']);
});

$response = $this->soapWrapper->call('SERVICE_NAME.FUNCTION_NAME', [$params]);
```
