### ISSUE TITLE
Soap is not installing on Laravel 5.4

### ISSUE THREAD

**Issue by THEMBOCHARLES** [artisaninweb/laravel-soap#116]
This is what Is get

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.28
    - Conclusion: don't install laravel/framework v5.4.28
    - Conclusion: don't install laravel/framework v5.4.27
    - Conclusion: don't install laravel/framework v5.4.26
    - Conclusion: don't install laravel/framework v5.4.25
    - Conclusion: don't install laravel/framework v5.4.24
    - Conclusion: don't install laravel/framework v5.4.23
    - Conclusion: don't install laravel/framework v5.4.22
    - Conclusion: don't install laravel/framework v5.4.21
    - Conclusion: don't install laravel/framework v5.4.20
    - Conclusion: don't install laravel/framework v5.4.19
    - Conclusion: don't install laravel/framework v5.4.18
    - Conclusion: don't install laravel/framework v5.4.17
    - Conclusion: don't install laravel/framework v5.4.16
    - Conclusion: don't install laravel/framework v5.4.15
    - Conclusion: don't install laravel/framework v5.4.14
    - Conclusion: don't install laravel/framework v5.4.13
    - Conclusion: don't install laravel/framework v5.4.12
    - Conclusion: don't install laravel/framework v5.4.11
    - Conclusion: don't install laravel/framework v5.4.10
    - Conclusion: don't install laravel/framework v5.4.9
    - Conclusion: don't install laravel/framework v5.4.8
    - Conclusion: don't install laravel/framework v5.4.7
    - Conclusion: don't install laravel/framework v5.4.6
    - Conclusion: don't install laravel/framework v5.4.5
    - Conclusion: don't install laravel/framework v5.4.4
    - Conclusion: don't install laravel/framework v5.4.3
    - Conclusion: don't install laravel/framework v5.4.2
    - Conclusion: don't install laravel/framework v5.4.1
    - laravelcollective/html v5.2 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.1 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.2 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.3 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.4 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.5 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - laravelcollective/html v5.2.6 requires illuminate/view 5.2.* -> satisfiable by illuminate/view[v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7].
    - don't install illuminate/view v5.2.0|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.19|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.21|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.24|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.25|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.26|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.27|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.28|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.31|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.32|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.37|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.43|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.45|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.6|don't install laravel/framework v5.4.0
    - don't install illuminate/view v5.2.7|don't install laravel/framework v5.4.0
    - Installation request for laravel/framework 5.4.* -> satisfiable by laravel/framework[v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.3, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9].
    - Installation request for laravelcollective/html 5.2.* -> satisfiable by laravelcollective/html[v5.2, v5.2.1, v5.2.2, v5.2.3, v5.2.4, v5.2.5, v5.2.6].

**Comment by artisaninweb** [comment]
Don't think this is a issue created by this package.
This package requires PHP >= 5.4.0
And the Soap extension for PHP.
