### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by hurbanom** [artisaninweb/laravel-soap#124]
I have an error when I tried to install another laravel package or make composer update:

```
Problem 1
    - The requested package artisaninweb/laravel-soap (locked at 0.2.5.10, required as 0.3.*) is satisfiable by artisaninweb/laravel-soap[0.2.5.10] but these conflict with your requirements or minimum-stability.
```

I have installed Php 5.6.4

Thanks

**Comment by artisaninweb** [comment]
This is not a package error.
Please check your composer file for the correct version ect.
