### ISSUE TITLE
how send xml when invoke the call.

### ISSUE THREAD

**Issue by moraoscar** [artisaninweb/laravel-soap#126]
Hi, I try to consumer the next SoapService http://200.41.57.109:8086/m4.in.wsint/services/M4WSIntSR?wsdl specifically the method sendSMS, but always return error -105 same of the service, this error make reference can't logged because the credential are invalid, but the creadential are good and the support of company services verified the information. So I decide, testing the service and credencial the Boomerang Soap in google chrome and this working perfectly with the next body:

<x:Envelope xmlns:x="http://schemas.xmlsoap.org/soap/envelope/" xmlns:cor="http://core.ws.m4.tedexis.com">
    <x:Header/>
    <x:Body>
        <cor:sendSMS>
            <cor:passport>?</cor:passport>
            <cor:password>?</cor:password>
            <cor:number>?</cor:number>
            <cor:text>?</cor:text>
        </cor:sendSMS>
    </x:Body>
</x:Envelope>

Then my cuestion is, how send this body with your soapwrapper? I hope you can help me.

Thanks.

**Comment by artisaninweb** [comment]
You need a custom header for this.

```php
$this->soapWrapper->add('Currency', function ($service) {
      $service
        ->customHeader(--PUT-HEADER-HERE--);
    });
```
