### ISSUE TITLE
how i attach document with soap call

### ISSUE THREAD

**Issue by musman92** [artisaninweb/laravel-soap#128]

**Comment by whfamily2006** [comment]
@musman92  please write here the steps/procedure if you got any success...?
and soap api call required document or image document base 64 code?

**Comment by musman92** [comment]
@whfamily2006 
`$wsdl = "https://demo-ipg.comtrust.ae:2443/MerchantAPIX.svc?singleWsdl";`
`$opts = array(
     'ssl' => array(
         'local_cert' => 'F:\usman\emendoobi_erd\cert.pem',
         'passphrase' => 'Comtrust',
         'ciphers' => 'RC4-SHA',
         'verify_peer' => false,
         'verify_peer_name' => false,
     //'local_cert' => '.\Demo Merchant.pfx',
     ),
     'local_cert' => 'F:\usman\emendoobi_erd\cert.pem',
 );`

`
$client = new SoapClient($wsdl, $opts);
$search_query = new \StdClass();
$search_query->request = new \StdClass();
$search_query->request->Customer = 'Demo Marchent';
$search_query->request->Language = 'en';
$search_query->request->AccountNumber = '4111111111111111';
$search_query->request->Amount = '100';
$search_query->request->Currency = 'AED';
$search_query->request->ExpiryDate = '2020-01';
$search_query->request->OrderID = '123456';
$search_query->request->OrderInfo = 'test';
$search_query->request->OrderName = 'test ';
$search_query->request->TransactionHint = 'CPT:Y';
$search_query->request->VerifyCode = '123';

$result = $client->Authorize($search_query);
echo '<pre>';
var_dump($result);
`
