### ISSUE TITLE
NTLM Support?

### ISSUE THREAD

**Issue by benyanke** [artisaninweb/laravel-soap#129]
Does this package support NTLM auth, for use with Microsoft Soap services? I'm having trouble finding anything about it in the repo, so I'm assuming not, but I may have missed it.

**Comment by benyanke** [comment]
Update: I was able to get my application working with the jamesiarmes/php-ntlm package, which provides a new SoapClient function to use.

Is there (or could there be) an easy way to specify an alternate soap client function?

**Comment by artisaninweb** [comment]
```php
$this->soapWrapper->add('Currency', function ($service) {
      $service->client(--PUT-CLIENT-HERE---);
    });
```
