### ISSUE TITLE
how to make a request 

### ISSUE THREAD

**Issue by xhava** [artisaninweb/laravel-soap#13]
please @artisaninweb  could you help me, how can maka a request with the next structure : 
<Request>

	<PosLogin>

		<PosName>434343</PosName>

		<UserName>33434</UserName>

		<UserPass>c32d196fea8fcc528dfcb65456829b20</UserPass>

	</PosLogin>

	<PosMethod>

		<MethodName>ReservaTopUp</MethodName>

		<Params>

			<CountryCode>32</CountryCode>

			<PhoneNumber>343434</PhoneNumber>

			<CardID>3434</CardID>

		</Params>

	</PosMethod>

</Request>

**Comment by artisaninweb** [comment]
The data given to the call must be in the same structure like you'r xml, something like:

```php
$data = [
    'PosLogin' => [
        'PosName' => '',
        'UserName' => '',
        'UserPass' => '',
    ],
    'PosMethod' => [
        'MethodName' => '',
        'Params' => [
            'CountryCode' => '',
            'CountryCode' => '',
            'CardID' => '',
        ]
    ]
];
```

**Comment by artisaninweb** [comment]
I'm gonna close this issue if you got more questions please let me know.

**Comment by xhava** [comment]
Thanks a lot, it works.
