### ISSUE TITLE
SoapFault: no UserCredentials in SOAP Header

### ISSUE THREAD

**Issue by unpherum** [artisaninweb/laravel-soap#130]
I got this error message
`SoapFault: no UserCredentials in SOAP Header in file /var/www/html/MyProjectFolder/vendor/artisaninweb/laravel-soap/src/Artisaninweb/SoapWrapper/Client.php on line 189`

and my header is:

```
$auth_params = new stdClass();
$auth = new stdClass();
$auth->userid = $this->userid;
$auth->password = $this->password;
$auth_params->UserCredentials = $auth;
    		
$header_params = new SoapVar($auth_params, SOAP_ENC_OBJECT);
->header($this->ns, $this->appName, $header_params, false, null)
```
Pretty sure I have done something wrong, but I am not sure what is the correct one. please kindly help to see what should it be. how can i construct the header for Auth. and end point showing this document I should have sent this to them. so i don't know if I have reach them yet and got this error from them or the request is not yet out to any where.
```
<soap:Header>
         <UserCredentials>
                  <userid>user</userid>
                  <password>password</password>
         </UserCredentials>
</soap:Header>
```

**Comment by unpherum** [comment]
Hmmm just realized later that I put the wrong ns, I did with build in soapClient for PHP and it works but will do again with this wrapper later. should be fine.

**Comment by unpherum** [comment]
Hmmm just realized later that I put the wrong ns, I did with build in soapClient for PHP and it works but will do again with this wrapper later. should be fine.

**Comment by LittleBitGirl** [comment]
I have the same issue, did you solve it with wrapper?
