### ISSUE TITLE
Client : getCookies method

### ISSUE THREAD

**Issue by devkdouglass** [artisaninweb/laravel-soap#133]
**Current Code**
```
public function getCookies()
  {
    return $this->__cookies;
  }
```

**Should Be**
```
public function getCookies()
  {
    return $this->__getCookies();
  }
```

**Comment by artisaninweb** [comment]
If i look at the documention: http://php.net/manual/en/class.soapclient.php
The function __getCookies() does not exist, so i don't think it's correct.
If you can provide me with proper documention i will take a look at it.
