### ISSUE TITLE
How can I show the results

### ISSUE THREAD

**Issue by rllapur89** [artisaninweb/laravel-soap#144]
Hi Sr. I think your code it's fine but I can't find how can I show the results if I can't find the view in your code. In that case, how can I do the view to show the data? Thanks in advance

**Comment by rechim** [comment]
Well you use it just to make the request.
If you want to display the data to user u have to save the response in the database and create a controler for it to display it.
For example I had to deal with an order system and had to make calls to check the order.
The response from the check was saved on the order object and displayed onto order show page.
Maybe it helps in your situation too.
Happy coding.

**Comment by artisaninweb** [comment]
You can find your answer in the readme file.
See "usage".
