### ISSUE TITLE
Call Soap << Object of class stdClass could not be converted to string >> 

### ISSUE THREAD

**Issue by JohnHerve** [artisaninweb/laravel-soap#145]
in my file .wsdl have : <xs:element maxOccurs="unbounded" minOccurs="0" name="validatedParameter" nillable="true" type="ns:ArrayOfString"/>

I created service ValidateEmailService use validate Request and Response, in fuction Response i return to string " OK - success ".
In console i run "php artisan soap:test" but it's error : "Object of class stdClass could not be converted to string",  but when i change type="ns:ArrayOfString" to "xs:string" ,it's success.Help me pls!!!

**Comment by artisaninweb** [comment]
Can you show me the code in your command?

**Comment by JohnHerve** [comment]
in folder App\Soap:
class ValidateEmailService
{
    /**
     * @param validateEmail $validateEmail
     * @return validateEmailResponse
     */
    public function validateEmail($validateEmail){
        return new validateEmailResponse('OK - validateEmail');
    }
}

In app\Console\Commands\CallSoap.php

class CallSoap extends Command
{
     protedted $signature = 'soap:test';
    public function handle(){
 $this->output->writeln('TEST');
        $soap = new SoapWrapper();
        $appUrl = config('soap.APP_URL');
        $soap->add('ValidateEmailService', function (\Artisaninweb\SoapWrapper\Service $service) use ($appUrl) {
            $service->wsdl($appUrl . '/ValidateEmailService?wsdl')
                ->trace(true)
                ->classMap([
                    validateEmail::class,
                    validateEmailResponse::class
                ]);
        });

        $result = $soap->call('ValidateEmailService.validateEmail', [
            new validateEmail('clientInfo','validatedParameter')
        ]);

        echo $result->getReturn();
}
}

and in console , i run : "php artisan soap:test"

**Comment by artisaninweb** [comment]
The error is in your command.
You can not echo a array.

Replace it with: 
```php 
echo print_r($result->getReturn());
```
