### ISSUE TITLE
"message": "SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://sandbox-ops.xx:7001/Igate_WS/Route?wsdl' : failed to load external entity \"https://sandbox-ops.xx:7001/Igate_WS/Route?wsdl\"\n",

### ISSUE THREAD

**Issue by altdev91** [artisaninweb/laravel-soap#148]
Hello.
When I test on local, my code is working but when i upload this code on VPS Centos 7, open port 7001, it show this error.

Can you help me? Thank you so much!

**Comment by artisaninweb** [comment]
You'r webserver can not access the url 'https://sandbox-ops.xx:7001/Igate_WS/Route?wsdl'.
I think this is a public url?
