### ISSUE TITLE
Could not connect to host

### ISSUE THREAD

**Issue by Donkeh68** [artisaninweb/laravel-soap#164]
Hello!
I am getting "Could not connect to host". Could somebody kindly help me?

My code:
`
namespace App\Http\Controllers;

use App\Library\Utilities;
use Carbon\Carbon;
use Artisaninweb\SoapWrapper\SoapWrapper;

class XXXController extends Controller
{
	/**
	 * @var SoapWrapper
	 */
	protected $soapWrapper;

	/**
	 * SoapController constructor.
	 *
	 * @param SoapWrapper $soapWrapper
	 */
	public function __construct(SoapWrapper $soapWrapper)
	{
		$this->soapWrapper = $soapWrapper;
	}

	/**
	 * Main function called by route
	 */
	public function SoapRequest1()
	{
		try {
			# INIT - VALUES ARE EXAMPLES
			$amount = '100';
			$order_id = '0000';
			$token = '1234';
			$auth_code = '9876';

			# CREATE SERVICE
			$this->soapWrapper->add('Secure3DLookup', function ($service) {
				$service
				->wsdl('http://inhifin.com.test/wsdl/PaymentGateway.wsdl')
				->trace(true)
				->cache(WSDL_CACHE_NONE)
				->certificate(true)
				->options([
					'local_cert'=> '/usr/lib/ssl/demoCA/InhifinDev.pem',
					'passphrase'=> 'XXXX',
					'stream_context' => stream_context_create([
						'ssl' => [
							'verify_peer' => false,
							'verify_peer_name' => false,
							'allow_self_signed' => true,
						],
					]),
				])
				->classmap([
					Secure3DLookup::class,
					Secure3DLookupResponse::class,
				]);
			});

			# CALL SERVICE
			$response = $this->soapWrapper->call('Secure3DLookup.Secure3DLookup', [
				'MerchantID'			=> getenv('ECENTRIC_MERCHANT_ID'),
				'TransactionID'			=> Utilities::generateGUID(),
				'TransactionDateTime'	=> Carbon::now(),
				'Amount'				=> $amount,
				'CurrencyCode'			=> getenv('ECENTRIC_CURRENCY'),
				'OrderNumber'			=> $order_id,
				'Token'					=> $token,
				'SecurityCode'			=> $auth_code,
			]);

			var_dump ($response);
			die();
		} catch (\Exception $e) {
			return $e->getMessage() . '<br />' . '<br />' . $e->getTraceAsString();
		}
	}
}
`
I have tested connection to the server, using the WSDL and my certificate, via SOAP-UI and it all works fine, so clearly I'm missing something in my PHP code. Maybe a header?
I would really appreciate any help!

**Comment by MujahidAbbas** [comment]
I am getting the same error, can anyone help here?

**Comment by Donkeh68** [comment]
The problem was that the host server was rejecting my certificates.
I tried resolving this using Soap and Curl in separate implementations, but, because my gateway service provider was unable to provide any real assistance with this issue, my solution was to switch to DPO PayGate - a gateway service provider not using certificate-based authentication.
My integration proceeded without further problem.
