### ISSUE TITLE
Laravel SOAP Endpoints

### ISSUE THREAD

**Issue by SmartPrac** [artisaninweb/laravel-soap#19]
Hey there

How would I go about changing the endpoints?

SoapWrapper::add(function ($service) {
			$service
				->name('submit')
				->wsdl('xxxxxxxxxxxxxxxxxxxxxxxxxxxx')
				->trace(true)                                                 
				->location('xxxxxxxxxxxxxxxxxxxxxx')
->cache(WSDL_CACHE_NONE);                                      
		});

**Comment by artisaninweb** [comment]
I don't know what you mean exactly, but i guess by adding multiple services?
