### ISSUE TITLE
Can't composer update to 0.3.0.10

### ISSUE THREAD

**Issue by toto33331** [artisaninweb/laravel-soap#196]
If I modify the requirement in composer.json to `"artisaninweb/laravel-soap": "0.3.*"` it installs 0.3.0.9.
If I modify the requirement in composer.json to `"artisaninweb/laravel-soap": "0.3.0.10"` it says:
```
Root composer.json requires artisaninweb/laravel-soap 0.3.0.10, found artisaninweb/laravel-soap[dev-master, dev-develop, 0.1, ..., 0.3.0.9] but it does not match the constraint
```
If I modify the composer.lock to reference the commit 809073fe1116e3e3daadcf8571fc58b0a9603574 and do a `composer install`, it works but the next `composer update` will roll back to 0.3.0.9.

I did a composer `composer self-update`, `composer clear`, `composer clear-cache` but nothing changed

I also tried to require `"artisaninweb/laravel-soap": "dev-master"` that also installs 0.3.0.9
I tried using composer v1.10 also

**Comment by toto33331** [comment]
Nobody else have that error ? I tried to install on a new laravel app, and it's still 0.3.0.9 that's installed

**Comment by toto33331** [comment]
Nobody ?

**Comment by notfalsedev** [comment]
@toto33331 packagist did not have the new version, auto update did not work..
Please try again.

**Comment by toto33331** [comment]
Amazing! Thank you !
