### ISSUE TITLE
SOAP-ERROR: Parsing WSDL: Couldn't load from ...

### ISSUE THREAD

**Issue by ichbinedgar** [artisaninweb/laravel-soap#20]
Hi,
I'm new to SOAP, and the documentation of your "library" is very limited so I wanted to ask you why I'm receiving the following error (below); My WSDL xml file can be access by tipying the url in the browser, so I'm not sure if I did something wrong. 

SOAP-ERROR: Parsing WSDL: Couldn't load from "http://:..."
WSDL' : failed to load external entity "http://"

this is my code
```php
SoapWrapper::add(function ($service) {
            $service
                ->name('getItemRequest')
                ->wsdl('http://xxxxxxxxxxxx?WSDL')
                ->trace(true)                                                   // Optional: (parameter: true/false)
                //->header()// Optional: (parameters: $namespace,$name,$data,$mustunderstand,$actor)
                //->cookie()                                                      // Optional: (parameters: $name,$value)
                //->location()                                                    // Optional: (parameter: $location)
                ->cache(WSDL_CACHE_NONE)                     // Optional: Set the WSDL cache
                ->options(['proxy_host' => "xxxxxxx", 'proxy_port'=> 000,'proxy_login'=> "###",'proxy_password' => "xxxxx"]);// Optional: Set some extra options
        });
```
I needed it to set the proxy configuration because at the beginning I was receiving the following error:
SOAP-ERROR: Parsing Schema: can't import schema from 'http://www.w3.org/2005/05/xmlmime'
This was solved, but now I received the other error. I tried to search info about this, but I have not found anynthing useful yet.

My xml envelope is like this:
```xml
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" 
xmlns:int="http://webservice.mks.com/10/Integrity" 
xmlns:sch="http://webservice.mks.com/10/Integrity/schema">
   <soapenv:Header/>
   <soapenv:Body>
      <int:getItem>
         <!--Optional:-->
         <arg0 transactionId="?" sch:ItemId="11111">
            <sch:Username>xxxxx</sch:Username>
            <sch:Password>xxxxxx</sch:Password>
            <!--Zero or more repetitions:-->
            <sch:InputField>Summary</sch:InputField>
         </arg0>
      </int:getItem>
   </soapenv:Body>
</soapenv:Envelope>
```
Thanks! :)

**Comment by artisaninweb** [comment]
I think this has nothing to do with my soap-wrapper, i think your wsdl is incorrect.
Do you get the same error if you use the SoapClient from PHP?

**Comment by ichbinedgar** [comment]
Hi artisanweb! my wsdl is correct. I didn't use PHP SoapClient, but I got it to work using curl. so I don't know why is not working. it maybe some proxy problem. Thanks anyway.

I used the coded of this stakcoverflow answer 
http://stackoverflow.com/questions/3006977/how-can-i-send-soap-xml-via-curl-and-php

**Comment by artisaninweb** [comment]
It's very difficult for me to check whats wrong here.
I don't think it's in the SoapWrapper but if you find a bug please let me know.
For now i'm gonna close this issue, hope you can sort it out.

**Comment by ichbinedgar** [comment]
Thanks, yep. I will let you know.
