### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by summit-web** [artisaninweb/laravel-soap#21]
Hey,

I might be doing this wrong.  I uploaded your module to the vendors folder and then followed your 'installation' process. I now get this error:

Class 'Artisaninweb\SoapWrapper\ServiceProvider' not found

Any idea what I could be doing wrong?
Thanks in advance!

**Comment by summit-web** [comment]
Think I have it fixed:

I had to update my autoload_classmap.php with

`'Artisaninweb\\SoapWrapper\\ServiceProvider' => $vendorDir . '/Artisaninweb/SoapWrapper/ServiceProvider.php'`

Thanks - time to make this work with my external API now. Sorry about the disruption!

**Comment by artisaninweb** [comment]
Let composer take care of that for you :)
See: https://getcomposer.org/
