### ISSUE TITLE
Nil results when query appears right

### ISSUE THREAD

**Issue by summit-web** [artisaninweb/laravel-soap#22]
Previously with SOAP in a PHP application I've used the in-built PHP SoapClient() functions. When I set up the client and then apply

`$client->CheckMemberID(array('memberID'=>$memberID));
 $returned_result = $result->CheckMemberIDResult`

I get a result.

In your soap for Laravel:

$data = [
            'memberID' => $memberId
        ];

`SoapWrapper::service('validMemberId', function ($service) use ($data) {
         var_dump($service->call('CheckMemberID', $data)->CheckMemberIDResult);
        });`

I get an empty array.

I've debugged this far - so I know it's connecting and the SOAP Client authorises fine (The AuthHeader is being passed fine).

It's just this final step- any help gratefully received! Thanks!

**Comment by artisaninweb** [comment]
Have you tried this: `$service->call('CheckMemberID', [$data])->CheckMemberIDResult`.

**Comment by summit-web** [comment]
Ah that's it, I'm getting my record now.

last question, then I'll leave you in peace! I need to assign that result to a variable for returning the value outside the function but I can't seem to do it, e.g.

`SoapWrapper::service('validMemberId', function ($service) use ($data) {
            //var_dump($service->getFunctions());
         $this->$returned_result = $service->call('CheckMemberID', [$data])->CheckMemberIDResult;
        });
  if($returned_result==$memberId){
   return $returned_result;  
  }
  else{
   return 'Fail: ('.$this->$returned_result.')';  
  }`

Do I need to do my if/else inside your SoapWrapper::service function?

**Comment by artisaninweb** [comment]
`$this->$returned_result` must be `$this->returned_result` i think?
Maybe this will help: http://stackoverflow.com/questions/25717810/laravel-soap-cant-get-the-response-outside-of-the-wrapper

**Comment by summit-web** [comment]
Thanks, really helpful. My final wrapper was

`SoapWrapper::service('validMemberId', function ($service) use ($data,$memberId) {
         //var_dump($service->getFunctions());
         $returned_result = $service->call('CheckMemberID', [$data])->CheckMemberIDResult;
         if($returned_result==$memberId){
          return $returned_result;  
         }
         else{
          return 'Fail: ('.$returned_result.')';  
         }
        });`

I needed to bring in my input $memberId to compare... $this-> actually through an 'empty result' error, weirdly. Looks like the overall function can use a return from your ::service() function, so all's well!

Thanks for your help! :) :+1:
