### ISSUE TITLE
Failing to Validate Again (Probably my fault)

### ISSUE THREAD

**Issue by summit-web** [artisaninweb/laravel-soap#23]
```
$data = [
            'memberID' => $memberId
        ];

        // Using the added service
        SoapWrapper::service('validMemberId', function ($service) use ($data,$memberId) {
         //var_dump($service->getFunctions());
         $returned_result = $service->call('CheckMemberID', [$data])->CheckMemberIDResult;
         if($returned_result==$memberId){
          //return $returned_result;
          return 'ok';
        exit;
         }
         else{
          //return 'Fail: ('.$returned_result.')';
          return 'fail';
        exit;
         }
        });
  return 'conditions not met - '.$returned_result.' / '.$memberId; 
```

So there are no SOAP or Laravel errors being generated. I know the  `$memberId` being sent is correct because if I run this command outside Laravel I get this result:

`object(stdClass)#4 (1) { ["CheckMemberIDResult"]=> int(550474) }`

The issue is that $returned_result is not receiving the result of `$service->call`

Additionally the else{} statement is not being triggered, which I find plain odd.

Any ideas - and thank you for your patience - as this is undoubtedly my fault :) - thanks for providing this interface though as it makes connecting to a SOAP service really easy!

Martin

**Comment by summit-web** [comment]
I think the issue might be in how my two public functions are passing variables

mock up of code:

```public function number_one(){
 $memberId = "12345678";
 $is_member_valid = $this->is_member_valid($memberId);
}

public_function is_member_valid($memberId){
 // do SOAP Stuff
echo "yes";
 return "yes";
}```

The `return` value isn't ending up in $is_member_valid variable. Any idea why?

**Comment by artisaninweb** [comment]
You can't return the result like that because it's a closure, you need to pass-be-reference.
See: http://stackoverflow.com/questions/25717810/laravel-soap-cant-get-the-response-outside-of-the-wrapper

Try doing it like:
```php
$memberId = 10;
$data     = ['memberID' => $memberId];
$result   = null;

SoapWrapper::service('validMemberId', function ($service) use ($data, &$result) {
    $result = $service->call('CheckMemberID', [$data])->CheckMemberIDResult;
});

return 'The result from the call is:' . $result;
```

The `&` sign is for passing the $result var by reference.

**Comment by summit-web** [comment]
Thanks for that - I know that was more PHP tutoring than a 'bug' - because there was no bug, but I now understand the logic behind it - I've got the successful call made now - thank you :+1:
