### ISSUE TITLE
After update can't get response

### ISSUE THREAD

**Issue by kticka** [artisaninweb/laravel-soap#27]
Today I have updated from 0.2.5.7 to 0.2.5.8, and from this point my app stopped working, Im always getting -1 response. Downgrade to 0.2.5.7 helped to me. Is there significant changes that should be mentioned in readme?

**Comment by artisaninweb** [comment]
Can you figure out whats going wrong?

**Comment by kticka** [comment]
Ok, i'll try to check it this week.

**Comment by artisaninweb** [comment]
Can you try version: 0.2.5.9

**Comment by kticka** [comment]
Yup. Everything fine with 0.2.5.9 .
