### ISSUE TITLE
Server was unable to process request. ---> Procedure or function 'www2_ProductInfo' expects parameter '@Name', which was not supplied.

### ISSUE THREAD

**Issue by mro95** [artisaninweb/laravel-soap#28]
Server was unable to process request. ---> Procedure or function 'www2_ProductInfo' expects parameter '@Name', which was not supplied.

This error appeared in v0.2.5.8, my code works in v0.2.5.7.

**Comment by artisaninweb** [comment]
Can you try something please?
In de `service.php` on #218 change 

`return call_user_func([$this->client, $function], $params);`

into

`return call_user_func_array([$this->client, $function], $params);`

I think it's in here.

**Comment by mro95** [comment]
Yep, that fixed it.

**Comment by artisaninweb** [comment]
Thanks for testing it!
I've just released the fix in version: 0.2.5.9
