### ISSUE TITLE
Can't add ssl cipher to SoapClient

### ISSUE THREAD

**Issue by mro95** [artisaninweb/laravel-soap#30]
Hey,

For some weird reason, I have to add a SSL cipher into the SOAP option.
It's a weird bug that appeared a week ago, I think because I upgraded OpenSSL. more info: http://willbradley.name/2012/10/03/workaround-for-php-error-in-ubuntu-12-04-soapclient-ssl-crypto-enabling-timeout/

Problem is I can't add stream_context_create when I am using SoapService Model.
For example this isn't possible:
```
protected $options = stream_context_create(array('foo'=>'bar'));
```

**Comment by artisaninweb** [comment]
```
protected $options; // Must be a array
``` 
If i'm correct you can add options like so in you model:
```
protected $options = ['stream' => stream_context_create(array('foo'=>'bar'))];
```

Or by calling the options function for that
```
$options = ['stream' => stream_context_create(array('foo'=>'bar'))];

$model = new ModelExtendsSoapService();
$model->options($options);
```

Can you try this?

**Comment by mro95** [comment]
I've tried it but it doesn't work because the function createClient has been called in the constructor of SoapService.

**Comment by artisaninweb** [comment]
Then you need to do something like this:
```
use Artisaninweb\SoapWrapper\Extension\SoapService;

class Model extends SoapService {

    /**
     * @param array $options
     */
    public function __construct(array $options)
    {
        $this->options($options);

        parent::__construct();
    }

}
```

```
$options = ['stream' => stream_context_create(array('foo'=>'bar'))];

new Model($options);
```

**Comment by mro95** [comment]
Ah it works. Thanks!!
