### ISSUE TITLE
SoapFault exception: [HTTP] Could not connect to host

### ISSUE THREAD

**Issue by dharmendrajadon** [artisaninweb/laravel-soap#31]
I keep receiving this error every time. My wsdl file: http://retina.cannybee.in/services.wsdl
Can you please check it once
#0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://202.78.1...', 'http://tempuri....', 1, 0)
#1 [internal function]: SoapClient->__call('UploadData', Array)
#2 [internal function]: SoapClient->UploadData(Array)

**Comment by artisaninweb** [comment]
Sorry for the late response.
Did you figure out the problem?
