### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by arifw3** [artisaninweb/laravel-soap#32]
I have an error,
Missing argument 1 for Artisaninweb\SoapWrapper\Service::header(),

Thanks

**Comment by mro95** [comment]
Can you be more specific? Show us you code?

**Comment by Sandldan** [comment]
This happens when you run demo() in the SoapController example directly. In the service you're adding, just comment out the lines where you don't have any optional parameters to add :)

**Comment by unpherum** [comment]
@artisaninweb @Sandldan 
Yes comenting out the header is fine, but what if I wanna use header? I have put the params for header, but it say "Missing argument 2 for Artisaninweb/So....Service:header()"

please help, here is my header

    	

> $auth_params = new stdClass();
>     	$auth_params->userid = $this->userid;
>     	$auth_params->password = $this->password;
> 
>     	$header_params = new SoapVar($auth_params, SOAP_ENC_OBJECT);
>     	$this->header = new SoapHeader($this->appName, 'UserCredentials', $header_params, false);
