### ISSUE TITLE
Always String 0 or float -1

### ISSUE THREAD

**Issue by panelo** [artisaninweb/laravel-soap#35]
Can you please help me. Trying to test it in both Laravel 4.2 and Laravel 5 but can't get it to work. Did I miss anything?

http://www.webservicex.net/CurrencyConvertor.asmx?op=ConversionRate

Here's my Controller

    <?php 
    use Artisaninweb\SoapWrapper\Facades\SoapWrapper;
    
    class SoapController extends BaseController {
        public function demo()
        {
		    SoapWrapper::add(function ($service) {
		        $service->name('ConversionRate')->wsdl('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL');
		    });
		
		    $data = [
		        'FromCurrency' => 'AUD',
		        'ToCurrency'   => 'USD'
		    ];
		
		    SoapWrapper::service('ConversionRate', function ($service) use ($data) {
                var_dump($service->getFunctions());
                var_dump($service->call('ConversionRate',$data)->ConversionRateResult);
            });
        }
    }

And here's the output.

    array(2) { [0]=> string(65) "ConversionRateResponse ConversionRate(ConversionRate $parameters)" [1]=> string(65) "ConversionRateResponse ConversionRate(ConversionRate $parameters)" } float(-1)

**Comment by panelo** [comment]
Returns "0" in your example as well (Laravel 4.2)

    <?php 

    use Artisaninweb\SoapWrapper\Facades\SoapWrapper;

    class SoapController extends BaseController {

       public function demo()
        {
		    SoapWrapper::add(function ($service) {
		        $service->name('currency')->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL');
		    });
		
		    $data = [
		        'CurrencyFrom' => 'USD',
		        'CurrencyTo'   => 'EUR',
		        'RateDate'     => '2014-06-05',
		        'Amount'       => '1000'
		    ];
		
		    SoapWrapper::service('currency',function($service) use ($data) {
		        var_dump($service->getFunctions());
		        var_dump($service->call('GetConversionAmount',$data)->GetConversionAmountResult);
		    });
        }
    }

Output

    array(16) { [0]=> string(62) "GetCurrenciesResponse GetCurrencies(GetCurrencies $parameters)" [1]=> string(68) "GetCurrencyRateResponse GetCurrencyRate(GetCurrencyRate $parameters)" [2]=> string(71) "GetCurrencyRatesResponse GetCurrencyRates(GetCurrencyRates $parameters)" [3]=> string(74) "GetConversionRateResponse GetConversionRate(GetConversionRate $parameters)" [4]=> string(80) "GetConversionAmountResponse GetConversionAmount(GetConversionAmount $parameters)" [5]=> string(65) "GetCultureInfoResponse GetCultureInfo(GetCultureInfo $parameters)" [6]=> string(89) "ConvertDataTableColumnResponse ConvertDataTableColumn(ConvertDataTableColumn $parameters)" [7]=> string(74) "GetLastUpdateDateResponse GetLastUpdateDate(GetLastUpdateDate $parameters)" [8]=> string(62) "GetCurrenciesResponse GetCurrencies(GetCurrencies $parameters)" [9]=> string(68) "GetCurrencyRateResponse GetCurrencyRate(GetCurrencyRate $parameters)" [10]=> string(71) "GetCurrencyRatesResponse GetCurrencyRates(GetCurrencyRates $parameters)" [11]=> string(74) "GetConversionRateResponse GetConversionRate(GetConversionRate $parameters)" [12]=> string(80) "GetConversionAmountResponse GetConversionAmount(GetConversionAmount $parameters)" [13]=> string(65) "GetCultureInfoResponse GetCultureInfo(GetCultureInfo $parameters)" [14]=> string(89) "ConvertDataTableColumnResponse ConvertDataTableColumn(ConvertDataTableColumn $parameters)" [15]=> string(74) "GetLastUpdateDateResponse GetLastUpdateDate(GetLastUpdateDate $parameters)" } string(1) "0"

**Comment by artisaninweb** [comment]
Have you tried this?

```
var_dump($service->call('GetConversionAmount', [$data])->GetConversionAmountResult);
```

**Comment by panelo** [comment]
that works awesome! Follow-up silly question. Can you let me know how do I remove the word string on the output?

    string(30) "737.08262696248249428760964100"

Just wanted the numbers

    737.08262696248249428760964100

**Comment by panelo** [comment]
it works! awesome. thanks!
