### ISSUE TITLE
Unable connect to host error, when

### ISSUE THREAD

**Issue by aivarasru** [artisaninweb/laravel-soap#36]
Unable connect to host when using WSDL host uses port.
I`ve solved this issue by modifying getOptions() method to: 
<code>
public function getOptions()
  {
    $options = [
      'proxy_host' => parse_url($this->getWsdl(), PHP_URL_HOST),
      'proxy_port' => parse_url($this->getWsdl(), PHP_URL_PORT),
      'trace'      => $this->getTrace(),
      'cache_wsdl' => $this->getCache()
    ];

```
if ($this->certificate) {
  $options['local_cert'] = $this->certificate;
}

$this->options = array_merge($options, $this->options);

return $this->options;
```

  }
</code>

**Comment by artisaninweb** [comment]
Can you make a pull-request for this?

**Comment by artisaninweb** [comment]
Can't you just use the port in the url?
`http://currencyconverter.kowabunga.net:1234/converter.asmx?WSDL`

Else you can always use the options([]) methode for this.
