### ISSUE TITLE
Not able to use it in non-WSDL mode without hack

### ISSUE THREAD

**Issue by oppiansteve** [artisaninweb/laravel-soap#38]
I had to bypass the `SoapService` constructor and create the client myself to avoid the thrown exception.
Instead, I just have `$this->createClient();` to initialise the client.

But following this 'hack', I could use the service OK.

It would be good if laravel-soap supported non-WSDL mode by default.

**Comment by artisaninweb** [comment]
I've fixed this in version 0.3.*.
