### ISSUE TITLE
Error while calling the wsdl !

### ISSUE THREAD

**Issue by Moutaouakil** [artisaninweb/laravel-soap#40]
when i call the method that contains the SoapWrapper code , i get this error : 

SOAP-ERROR: Parsing WSDL: Missing <message> with name 'ns:null'

**Comment by artisaninweb** [comment]
Can you send the code your using plus the WSDL?

**Comment by Moutaouakil** [comment]
here's the php code : 

// Add a new service to the wrapper
		       SoapWrapper::add(function ($service) {
		           $service
		               ->name('HartiSystemResponse')
		               ->wsdl('http://195.154.161.76:8080/harti_system_web_service_v1/services/Main?wsdl')
		               ->cache(WSDL_CACHE_NONE)                                        // Optional: Set the WSDL cache
		               ->options(['login' => 'username', 'password' => 'password']);   // Optional: Set some extra options
		       });
			
	
		       $data = [
		           'isNer' => 'false',
		           'questionUser'   => 'puis-je intenter une action laquelle',
		           'corpusPath'     => 'Avocats/droit-penal'
		       ];

		       // Using the added service
              SoapWrapper::service('HartiSystemResponse', function ($service) use ($data) {
                  var_dump($service->getFunctions());
                  var_dump($service->call('HartiSystem', [$data])->HartiSystemResponse);
              });
=========================================================


And here's the wsdl : 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://harti.expenli.com" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns1="http://org.apache.axis2/xsd" xmlns:ax27="http://queryParser.lucene.apache.org/xsd" xmlns:ax29="http://ws.apache.org/axis2/xsd" xmlns:ax211="http://highlight.search.lucene.apache.org/xsd" xmlns:ax23="http://harti.expenli.com/xsd" xmlns:ax25="http://sax.xml.org/xsd" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ax21="http://io.java/xsd" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://harti.expenli.com">
<wsdl:documentation>Please Type your service description here</wsdl:documentation>
<wsdl:types>
<xs:schema xmlns:ax28="http://queryParser.lucene.apache.org/xsd" xmlns:ax212="http://highlight.search.lucene.apache.org/xsd" xmlns:ax210="http://ws.apache.org/axis2/xsd" xmlns:ax24="http://harti.expenli.com/xsd" xmlns:ax26="http://sax.xml.org/xsd" xmlns:ax22="http://io.java/xsd" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://harti.expenli.com">
<xs:import namespace="http://io.java/xsd"/>
<xs:import namespace="http://harti.expenli.com/xsd"/>
<xs:import namespace="http://sax.xml.org/xsd"/>
<xs:import namespace="http://queryParser.lucene.apache.org/xsd"/>
<xs:import namespace="http://ws.apache.org/axis2/xsd"/>
<xs:import namespace="http://highlight.search.lucene.apache.org/xsd"/>
<xs:element name="MainIOException">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="IOException" nillable="true" type="ax22:IOException"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="MainHARTIException">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="HARTIException" nillable="true" type="ax24:HARTIException"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="MainSAXException">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="SAXException" nillable="true" type="ax26:SAXException"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="MainParseException">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="ParseException" nillable="true" type="ax28:ParseException"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="HartiSystem">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="isNer" type="xs:boolean"/>
<xs:element minOccurs="0" name="questionUser" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="corpusPath" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="HartiSystemResponse">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="return" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="apprentissage">
<xs:complexType>
<xs:sequence>
<xs:element minOccurs="0" name="corpusPath" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="questionUser" nillable="true" type="xs:string"/>
<xs:element minOccurs="0" name="reponseFinal" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="aplatir">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="tab" nillable="true" type="ax29:TextFragment;"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="aplatirResponse">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="return" nillable="true" type="ax212:TextFragment"/>
</xs:sequence>
</xs:complexType>
</xs:element>
<xs:element name="main">
<xs:complexType>
<xs:sequence>
<xs:element maxOccurs="unbounded" minOccurs="0" name="args" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://ws.apache.org/axis2/xsd">
<xs:complexType name="TextFragment;">
<xs:sequence/>
</xs:complexType>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://highlight.search.lucene.apache.org/xsd">
<xs:complexType name="TextFragment">
<xs:sequence>
<xs:element minOccurs="0" name="fragNum" type="xs:int"/>
<xs:element minOccurs="0" name="score" type="xs:float"/>
<xs:element minOccurs="0" name="textEndPos" type="xs:int"/>
<xs:element minOccurs="0" name="textStartPos" type="xs:int"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://io.java/xsd">
<xs:complexType name="IOException">
<xs:sequence/>
</xs:complexType>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://queryParser.lucene.apache.org/xsd">
<xs:complexType name="ParseException">
<xs:sequence/>
</xs:complexType>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://harti.expenli.com/xsd">
<xs:complexType name="HARTIException">
<xs:sequence/>
</xs:complexType>
</xs:schema>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://sax.xml.org/xsd">
<xs:complexType name="SAXException">
<xs:sequence>
<xs:element minOccurs="0" name="cause" nillable="true" type="xs:anyType"/>
<xs:element minOccurs="0" name="exception" nillable="true"/>
<xs:element minOccurs="0" name="message" nillable="true" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
</wsdl:types>
<wsdl:message name="aplatirRequest">
<wsdl:part name="parameters" element="ns:aplatir"/>
</wsdl:message>
<wsdl:message name="aplatirResponse">
<wsdl:part name="parameters" element="ns:aplatirResponse"/>
</wsdl:message>
<wsdl:message name="HartiSystemRequest">
<wsdl:part name="parameters" element="ns:HartiSystem"/>
</wsdl:message>
<wsdl:message name="HartiSystemResponse">
<wsdl:part name="parameters" element="ns:HartiSystemResponse"/>
</wsdl:message>
<wsdl:message name="MainIOException">
<wsdl:part name="parameters" element="ns:MainIOException"/>
</wsdl:message>
<wsdl:message name="MainHARTIException">
<wsdl:part name="parameters" element="ns:MainHARTIException"/>
</wsdl:message>
<wsdl:message name="MainSAXException">
<wsdl:part name="parameters" element="ns:MainSAXException"/>
</wsdl:message>
<wsdl:message name="MainParseException">
<wsdl:part name="parameters" element="ns:MainParseException"/>
</wsdl:message>
<wsdl:message name="mainRequest">
<wsdl:part name="parameters" element="ns:main"/>
</wsdl:message>
<wsdl:message name="apprentissageRequest">
<wsdl:part name="parameters" element="ns:apprentissage"/>
</wsdl:message>
<wsdl:portType name="MainPortType">
<wsdl:operation name="aplatir">
<wsdl:input message="ns:aplatirRequest" wsaw:Action="urn:aplatir"/>
<wsdl:output message="ns:aplatirResponse" wsaw:Action="urn:aplatirResponse"/>
</wsdl:operation>
<wsdl:operation name="HartiSystem">
<wsdl:input message="ns:HartiSystemRequest" wsaw:Action="urn:HartiSystem"/>
<wsdl:output message="ns:HartiSystemResponse" wsaw:Action="urn:HartiSystemResponse"/>
<wsdl:fault message="ns:MainIOException" name="MainIOException" wsaw:Action="urn:HartiSystemMainIOException"/>
<wsdl:fault message="ns:MainHARTIException" name="MainHARTIException" wsaw:Action="urn:HartiSystemMainHARTIException"/>
<wsdl:fault message="ns:MainSAXException" name="MainSAXException" wsaw:Action="urn:HartiSystemMainSAXException"/>
<wsdl:fault message="ns:MainParseException" name="MainParseException" wsaw:Action="urn:HartiSystemMainParseException"/>
</wsdl:operation>
<wsdl:operation name="main">
<wsdl:input message="ns:mainRequest" wsaw:Action="urn:main"/>
<wsdl:output message="ns:null" wsaw:Action="urn:mainResponse"/>
<wsdl:fault message="ns:MainIOException" name="MainIOException" wsaw:Action="urn:mainMainIOException"/>
<wsdl:fault message="ns:MainHARTIException" name="MainHARTIException" wsaw:Action="urn:mainMainHARTIException"/>
<wsdl:fault message="ns:MainSAXException" name="MainSAXException" wsaw:Action="urn:mainMainSAXException"/>
<wsdl:fault message="ns:MainParseException" name="MainParseException" wsaw:Action="urn:mainMainParseException"/>
</wsdl:operation>
<wsdl:operation name="apprentissage">
<wsdl:input message="ns:apprentissageRequest" wsaw:Action="urn:apprentissage"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="MainSoap11Binding" type="ns:MainPortType">
<soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<wsdl:operation name="aplatir">
<soap:operation soapAction="urn:aplatir" style="document"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="HartiSystem">
<soap:operation soapAction="urn:HartiSystem" style="document"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
<wsdl:fault name="MainParseException">
<soap:fault use="literal" name="MainParseException"/>
</wsdl:fault>
<wsdl:fault name="MainHARTIException">
<soap:fault use="literal" name="MainHARTIException"/>
</wsdl:fault>
<wsdl:fault name="MainSAXException">
<soap:fault use="literal" name="MainSAXException"/>
</wsdl:fault>
<wsdl:fault name="MainIOException">
<soap:fault use="literal" name="MainIOException"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="main">
<soap:operation soapAction="urn:main" style="document"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body use="literal"/>
</wsdl:output>
<wsdl:fault name="MainParseException">
<soap:fault use="literal" name="MainParseException"/>
</wsdl:fault>
<wsdl:fault name="MainHARTIException">
<soap:fault use="literal" name="MainHARTIException"/>
</wsdl:fault>
<wsdl:fault name="MainSAXException">
<soap:fault use="literal" name="MainSAXException"/>
</wsdl:fault>
<wsdl:fault name="MainIOException">
<soap:fault use="literal" name="MainIOException"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="apprentissage">
<soap:operation soapAction="urn:apprentissage" style="document"/>
<wsdl:input>
<soap:body use="literal"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<wsdl:binding name="MainSoap12Binding" type="ns:MainPortType">
<soap12:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
<wsdl:operation name="aplatir">
<soap12:operation soapAction="urn:aplatir" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="HartiSystem">
<soap12:operation soapAction="urn:HartiSystem" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body use="literal"/>
</wsdl:output>
<wsdl:fault name="MainParseException">
<soap12:fault use="literal" name="MainParseException"/>
</wsdl:fault>
<wsdl:fault name="MainHARTIException">
<soap12:fault use="literal" name="MainHARTIException"/>
</wsdl:fault>
<wsdl:fault name="MainSAXException">
<soap12:fault use="literal" name="MainSAXException"/>
</wsdl:fault>
<wsdl:fault name="MainIOException">
<soap12:fault use="literal" name="MainIOException"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="main">
<soap12:operation soapAction="urn:main" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
<wsdl:output>
<soap12:body use="literal"/>
</wsdl:output>
<wsdl:fault name="MainParseException">
<soap12:fault use="literal" name="MainParseException"/>
</wsdl:fault>
<wsdl:fault name="MainHARTIException">
<soap12:fault use="literal" name="MainHARTIException"/>
</wsdl:fault>
<wsdl:fault name="MainSAXException">
<soap12:fault use="literal" name="MainSAXException"/>
</wsdl:fault>
<wsdl:fault name="MainIOException">
<soap12:fault use="literal" name="MainIOException"/>
</wsdl:fault>
</wsdl:operation>
<wsdl:operation name="apprentissage">
<soap12:operation soapAction="urn:apprentissage" style="document"/>
<wsdl:input>
<soap12:body use="literal"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<wsdl:binding name="MainHttpBinding" type="ns:MainPortType">
<http:binding verb="POST"/>
<wsdl:operation name="aplatir">
<http:operation location="aplatir"/>
<wsdl:input>
<mime:content type="application/xml" part="parameters"/>
</wsdl:input>
<wsdl:output>
<mime:content type="application/xml" part="parameters"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="HartiSystem">
<http:operation location="HartiSystem"/>
<wsdl:input>
<mime:content type="application/xml" part="parameters"/>
</wsdl:input>
<wsdl:output>
<mime:content type="application/xml" part="parameters"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="main">
<http:operation location="main"/>
<wsdl:input>
<mime:content type="application/xml" part="parameters"/>
</wsdl:input>
<wsdl:output>
<mime:content type="application/xml" part="parameters"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="apprentissage">
<http:operation location="apprentissage"/>
<wsdl:input>
<mime:content type="application/xml" part="parameters"/>
</wsdl:input>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="Main">
<wsdl:port name="MainHttpSoap11Endpoint" binding="ns:MainSoap11Binding">
<soap:address location="http://195.154.161.76:8080/harti_system_web_service_v1/services/Main.MainHttpSoap11Endpoint/"/>
</wsdl:port>
<wsdl:port name="MainHttpSoap12Endpoint" binding="ns:MainSoap12Binding">
<soap12:address location="http://195.154.161.76:8080/harti_system_web_service_v1/services/Main.MainHttpSoap12Endpoint/"/>
</wsdl:port>
<wsdl:port name="MainHttpEndpoint" binding="ns:MainHttpBinding">
<http:address location="http://195.154.161.76:8080/harti_system_web_service_v1/services/Main.MainHttpEndpoint/"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>

**Comment by artisaninweb** [comment]
Did you figure it out already?
It's very difficult for me to check what's wrong here.

**Comment by t3az0r** [comment]
I have the same issue: Some of the service implementation class methods (java on the server) returning (java) `void`.
The axis2 (java) framework generates from that:

```xml
...
        <wsdl:operation name="setCallbackEnabled">
            <wsdl:input message="ns:setCallbackEnabledRequest" wsaw:Action="urn:setCallbackEnabled"/>
            <wsdl:output message="ns:null" wsaw:Action="urn:setCallbackEnabledResponse"/>
            <wsdl:fault message="ns:APIOnlineImplException" name="APIOnlineImplException" wsaw:Action="urn:setCallbackEnabledAPIOnlineImplException"/>
        </wsdl:operation>
```

Which then produces `[WSDL] SOAP-ERROR: Parsing WSDL: Missing <message> with name 'ns:null'` when calling `$client = new SoapClient('my_wsdl.xml');`

Using the exact same wsdl file in a tool like SOAPUI (v5.7.0) works just fine...

So I wonder: "How to allow empty responses? Or: How to tell (php) SoapClient to understand `message="ns:null"` better?"

Cheers, tzr

**Comment by t3az0r** [comment]
Found a solution for my project: (kudos to Dan https://narkive.com/h6VLghV9.2)

1. I (manually) added an artificial `emptyElement` in my WSDL.xml file in the `<xs:schema` section:
```xml
            <!-- wsdl:definitions - wsdl:types - xs:schema - xs:element -->
            <xs:element name="emptyElement">
                <xs:complexType>
                    <xs:sequence/>
                </xs:complexType>
            </xs:element>
```
2.  I (manually) added artificial `wsdl:message` in my WSDL.xml file in the `<wsdl:definitions` section:
```xml
    <!-- wsdl:definitions - wsdl:message -->
    <wsdl:message name="setCallbackEnabledResponse">
        <wsdl:part name="parameters" element="ns:emptyElement"/>
    </wsdl:message>
```
3. Finally edited (manually) the line with the creepy `ns:null` value in the `<wsdl:operation` to:
```xml
            <!-- wsdl:definitions - wsdl:portType - wsdl:operation - wsdl:output -->
            <wsdl:output message="ns:setCallbackEnabledResponse" wsaw:Action="urn:setCallbackEnabledResponse"/>
```
So replacing `"ns:null"` with the _brand new_ `message` `"ns:setCallbackEnabledResponse"`.

After that my php SoapClient was able to parse the WSDL without ERRORs.

Cheers, tzr
