### ISSUE TITLE
How to pass element attributes, such as xsi:type

### ISSUE THREAD

**Issue by AlexFiorello** [artisaninweb/laravel-soap#41]
The structure of the XML request needs to contain and define a type, like this....

        <RequestDetails xsi:type="PostcodeRequest">
          <Postcode>BN12 123</Postcode>
        </RequestDetails>

How do I pass/define the xsi:type when making this request?

I have tried:

			     "RequestDetails" => [
					"RequestType" => "PostcodeRequest",
					"_" => [
						"Postcode" => $parameter
						]
					],

And without type:

				"RequestDetails" => [
					"Postcode" => $parameter
					],

Any suggestions are very much appreciated.  Thanks

**Comment by artisaninweb** [comment]
If i'm correct you can do it with: http://www.php.net/manual/en/soapvar.soapvar.php

**Comment by AlexFiorello** [comment]
Hi, thanks for your reply.  Yes I looked at this, but couldn't work out how to do it.

Would you have any idea how to SoapVar would slot into my example above?

**Comment by AlexFiorello** [comment]
Ok, thanks for your suggesstion.  I resolved it with the following:

    'RequestDetails' => new SoapVar(['Postcode' => $parameter], XSD_ANYTYPE, "PostcodeRequest", "http://llu.webservices.opalonline.co.uk/LineCharacteristicsWS", "RequestDetails"),

**Comment by geoidesic** [comment]
This didn't help me. It would be useful if @AlexFiorello could provide more complete code samples. E.g. what are you doing with this array you are building up? How are you passing it to the Service?

**Comment by KennyAAR2901** [comment]
I am also facing the same problem. But din't work what @AlexFiorello suggested.

Can anyone help me on this? 

I have to make an array in php of this xml

<objects>
              <ABCnxtObj> 
                   xsi:type="api:Lead" 
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <Key>702144</Key>
                <Custom>
                  <BusinessName>9<BusinessName>
                  </Custom>
               </ABCnxtObj>
            </objects>

I am not able to find a way to add xsi:type & xmlns:xsi to my array which I am sending to the Soap API

**Comment by inno3d** [comment]
An example for setting the xml Bericht  soapvar xsi:type, example;
<v33:Bericht xsi:type="v33:DataBinary" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
use:
$N_Bericht = new SoapVar(array($N_Data), SOAP_ENC_OBJECT, 'DataBinary', null, 'Bericht', $v33);
so use 3th param
