### ISSUE TITLE
Login should be first operation before any other reuqest

### ISSUE THREAD

**Issue by davejal** [artisaninweb/laravel-soap#42]
I'm trying to use this package, but I can't seem to login to a soap server. It is required to send a login operation before sending any other operation. Any help would be appreciated.

**Comment by mro95** [comment]
What code did you use to login?

**Comment by davejal** [comment]
Hi Maarten,
Eerste wat ik geprobeerd heb is
->options(['login' => 'username', 'password' => 'password']);

vervolgens heb ik getracht door:

 $data = [
            'user' => 'XXXX',
            'password'   => 'XXX',
            ];
SoapWrapper::service('currency', function ($service) use ($data) {
            var_dump($service->call('Login', [$data]));
        });

Maar neem aan dat bij het maken van de soapwrapper login informatie al meegestuurd moet worden of heb ik het fout?

alvast bedankt

**Comment by davejal** [comment]
het werkt, dns was down waardoor ik geen correcte response kreeg
