### ISSUE TITLE
WS-addressing

### ISSUE THREAD

**Issue by disto** [artisaninweb/laravel-soap#45]
Hi,

How do I add ws-addressing ?

thx

**Comment by artisaninweb** [comment]
I never really worked with ws-addressing but if i'm correct you can add it as custom headers.

**Comment by disto** [comment]
Hi, thx for replying, do you have a example how to add a custom header?

thx

**Comment by artisaninweb** [comment]
There is a function on the soap-service for custom headers:

```php
$customHeader = new SoapHeader(...);

SoapWrapper::add(function ($service) {
	$service
	    ->name('currency')
	    ->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL')
	    ->customHeader($customHeader);
});
```

**Comment by disto** [comment]
And the custom header is a array?

**Comment by artisaninweb** [comment]
```php
$customHeader1 = new SoapHeader(...); // <!-- The custom header 1
$customHeader2 = new SoapHeader(...); // <!-- The custom header 2

SoapWrapper::add(function ($service) use ($customHeader1, $customHeader2) {
    $service
        ->name('currency')
        ->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL')
        ->customHeader($customHeader1) // Custom header 1
        ->customHeader($customHeader2); // Custom header 1
});
```

**Comment by disto** [comment]
sorry, don’t know anything of SOAP and no time to learn :(
How do I add ws-addressing to a soap request?

**Comment by disto** [comment]
Hi Again,

I seem not to be able to get my soap requests to CIR (Centraal Insolventy Register) up and running.

This is the route to the WSDL file:
http://webservice.rechtspraak.nl/cir.asmx?WSDL

I can request all functions:

$WSDL   	= 'http://webservice.rechtspraak.nl/cir.asmx?WSDL';
$client 	= new SoapClient( $WSDL );
$result = $client->__getFunctions();
var_dump($result);

but when I try to use one of the functions, like:
$result = $client->searchInsolvencyID(array('insolvencyID' => 'F.10/13/519'));
var_dump($result);

I get this error message:
( ! ) Fatal error: Uncaught SoapFault exception: [q0:Security] Microsoft.Web.Services3.Security.SecurityFault: Header http://schemas.xmlsoap.org/ws/2004/08/addressing:Action for ultimate recipient is required but not present in the message. at Microsoft.Web.Services3.Design.RequireSoapHeaderAssertion.RequireSoapHeaderFilter.ProcessMessage(SoapEnvelope envelope) at Microsoft.Web.Services3.Pipeline.ProcessInputMessage(SoapEnvelope envelope) at Microsoft.Web.Services3.WseProtocol.FilterRequest(SoapEnvelope requestEnvelope) at Microsoft.Web.Services3.WseProtocol.RouteRequest(SoapServerMessage message) at System.Web.Services.Protocols.SoapServerProtocol.Initialize() at System.Web.Services.Protocols.ServerProtocolFactory.Create(Type type, HttpContext context, HttpRequest request, HttpResponse response, Boolean& abortProcessing) in /home/vagrant/sites/qvat-control/public/insolventieCheck.php:28 Stack trace: #0 /home/vagrant/sites/qvat-control/public/insolventieCheck.php(28): SoapClient->__call('searchInsolvenc...', A in /home/vagrant/sites/qvat-control/public/insolventieCheck.php on line 28

Can you help?
If you want to get paid for it, let me know how much.

Thx,
Dick Stokkel

PS:
Jij bent een Nederlander toch?
