### ISSUE TITLE
Separate the core classes

### ISSUE THREAD

**Issue by daison12006013** [artisaninweb/laravel-soap#49]
Upon checking your wrapper classes, it seems this is useful not just on Laravel Framework but also to other frameworks/micro such as Slim/Phalcon/Symfony and many more.

This project I think must only focused on the **Laravel** as a provider.

Hoping you could separate the class into a separated repository to be agnostic.

**Comment by artisaninweb** [comment]
I was thinking about this to.
I could make a ServiceProvider directory with some providers for different frameworks.
Will consider this in the next version.
