### ISSUE TITLE
I make the following request and still get Internal Server Error !!!

### ISSUE THREAD

**Issue by becology1100** [artisaninweb/laravel-soap#52]
SoapWrapper::add(function ($service) {
            $service
                ->name('Step_1_SearchCruises')
                ->wsdl('http://demo-cruisews.touricoholidays.com/CruiseServiceFlow.svc?wsdl')
                ->trace(true)                                                   // Optional: (parameter: true/false)
                ->options(['login' => 'xxxxxx', 'password' => 'xxxxxx', 'Culture' => 'en_US', 'Version' => '8']);   // Optional: Set some extra options
        });

        $data = [
            'CruiseLineID' => '1260327',
            'CruiseDestinationID'   => '51',
            'MarketCode'     => 'US',
            'Currency'       => 'USD',
            'DepartingFrom' => '2016-12-01',
            'DepartingTo' => '2016-12-27',
            'MinCruiseLength' => '0',
            'MaxCruiseLength' => '999',
            'PortID' => '3612',
            'ShipID' => '0',
            'IsSenior' => 'true',
            'IsInterline' => 'true',
            'IsMilitary' => 'true',
            'IsPastPassenger' => 'true'
        ];

        // Using the added service
        SoapWrapper::service('Step_1_SearchCruises', function ($service) use ($data) {
            print_r($service->getFunctions());
            var_dump($service->call('GetCruiseLines', [$data])->GetCruiseLinesResult);
        });

**Comment by artisaninweb** [comment]
I don't think this is in the package, but in the calls you make.
If you can show me otherwise i will take a look at it.
