### ISSUE TITLE
Usage as model extension

### ISSUE THREAD

**Issue by icibotaru** [artisaninweb/laravel-soap#53]
Hi,

More info as how to use SoapService as model, atm with the example from docs i get this error:
> Non-static method App\Soap::functions() should not be called statically, assuming $this from incompatible context

Thanks!

**Comment by artisaninweb** [comment]
You need to use the model in your controller;

``` use App\Model; ```

**Comment by pythondev1** [comment]
I also would like a bit more info on using in a model.
for example, I have a model that requires passing some options for SSL
'ssl' => array(
                    'verify_peer'   => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
I know how this can be done in a controller but not in a model and therefore I get unable to load errors on the WSDL, but putting these calls into a model would save me alot of lines of coding if possible.
