### ISSUE TITLE
Call to a member function __setLocation() on null

### ISSUE THREAD

**Issue by icibotaru** [artisaninweb/laravel-soap#54]
> FatalErrorException in Service.php line 348:
> Call to a member function __setLocation() on null

i get this when i add my location url to:

> ->location('https://....')

to fix this and make my add work i added location in:

> ->options(['location'=>'https://....'])

**Comment by artisaninweb** [comment]
Can you post your code here please?

**Comment by icibotaru** [comment]
Thanks!

**Comment by njtnestor** [comment]
It works for laravel 5.4?

**Comment by artisaninweb** [comment]
Laravel version 5.4 is not released yet, Laravel is on 5.2.

**Comment by njtnestor** [comment]
oh yes sorry! i mean 5.2

**Comment by artisaninweb** [comment]
It should work fine in 5.2.

**Comment by icibotaru** [comment]
Yes, i'm on Lumen 5.2 beside the known bugs all ok.

**Comment by njtnestor** [comment]
i get this error with the readme example:

FatalThrowableError in ControllerDispatcher.php line 110:
Fatal error: Call to undefined method cajas\Http\Controllers\SoapController::getMiddleware()

**Comment by icibotaru** [comment]
Please create a new issue, as this is the issue for my bug.
Thanks!

**Comment by artisaninweb** [comment]
Fixed in version 0.3.*
