### ISSUE TITLE
FatalThrowableError in Service.php line 356

### ISSUE THREAD

**Issue by njtnestor** [artisaninweb/laravel-soap#58]
FatalThrowableError in Service.php line 356:
Fatal error: Class 'SoapClient' not found

I' dont know what am i doing wrong
this is my controller:
`<?php
namespace cajas\Http\Controllers;
use Artisaninweb\SoapWrapper\Facades\SoapWrapper;

class SoapController extends controller{

```
public function demo()
{
    // Add a new service to the wrapper
    SoapWrapper::add(function ($service) {
        $service
            ->name('currency')
            ->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL');   
    });

    $data = [
        'CurrencyFrom' => 'USD',
        'CurrencyTo'   => 'EUR',
        'RateDate'     => '2014-06-05',
        'Amount'       => '1000'
    ];


}
```

}`

And the route: 

`Route::get('/demo', 'SoapController@demo');`

**Comment by manserod** [comment]
Hi! have you solve this problem?? I have same issue :(

**Comment by njtnestor** [comment]
No, I'm waiting for developer reply

**Comment by artisaninweb** [comment]
Which version of laravel-soap and Laravel do you use?

**Comment by asanluis** [comment]
Same over here, i use the last one(0.2.*), i also try using as model extension but always get a error

**Comment by artisaninweb** [comment]
Is the SoapClient for PHP installed on your server, you can check this by using the phpinfo() method.

**Comment by artisaninweb** [comment]
I've removed the model extention method in version 0.3.*
Please take a look a this new version, and let me know if there are any problems.

**Comment by ruchimes** [comment]
I have this issue right now.
I have Soap Client enabled in phpinfo and Don't know why this happens

**Comment by espetua** [comment]
Hi, I'm having this error too. I enabled the soap client and then restart Apache but is still wrong. What can I do? 
Thank you.
