### ISSUE TITLE
SoapFault in Service.php line 218

### ISSUE THREAD

**Issue by TheJeeky** [artisaninweb/laravel-soap#59]
Cannot process the message because the content type 'text/xml; charset=utf-8' was not the expected type 'application/soap+xml; charset=utf-8'.

**Comment by neoteknic** [comment]
+1 same error, but no more debug info

**Comment by chiefjs** [comment]
Try this
```
->options(['soap_defencoding' => 'UTF-8', 'soap_version'=> SOAP_1_2]);
```

**Comment by artisaninweb** [comment]
Did you figure out this issue?
If not please re-open this issue.
