### ISSUE TITLE
 Send XML as parameter data

### ISSUE THREAD

**Issue by rlaricor** [artisaninweb/laravel-soap#62]
Hi, I 'm using a webservice and I can not pass the information of this type :

`<![CDATA[<IN>
        <CONSULTA>
                <DNI>41304499</DNI>
        </CONSULTA>
        <IDENTIFICACION>
                <CODUSER>N00003</CODUSER>
                <CODTRANSAC>5</CODTRANSAC>  
                <CODENTIDAD>03</CODENTIDAD>
                <SESION>a8302129d43e0f0166054c0997c7de36a3daca76eea91650d1aae1ac73e47009e50a2ea6a84d773989332e6f60bf0fcc84dd9b1937264f1a20c6daf1310c257d</SESION>
        </IDENTIFICACION>
</IN>]]>
`

Please indicate what would be the procedure to send the data.

Greetings.

**Comment by artisaninweb** [comment]
Old issue, if you need information please let me know.
Closing issues for now.
