### ISSUE TITLE
Working locally and busting apache

### ISSUE THREAD

**Issue by yorianlara** [artisaninweb/laravel-soap#65]
When tried to run this code apache stop.

i'm usin laragon in local machine.

> namespace

>  App\Http\Controllers;

> use Artisaninweb\SoapWrapper\Facades\SoapWrapper;

> class SoapController extends Controller 

> {

    public function demo()
    {
        // Add a new service to the wrapper
        SoapWrapper::add(function ($service) {
            $service
                ->name('TASASCAMBIO')
                ->wsdl('https://casacambioserv-cert.extra.bcv.org.ve:443/service/autorizacion?wsdl')
                ->trace(true);                                                   // Optional: (parameter: true/false)
                //->header()                                                      // Optional: (parameters: $namespace,$name,$data,$mustunderstand,$actor)
                //->customHeader($customHeader);                                   // Optional: (parameters: $customerHeader) Use this to add a custom SoapHeader or extended class                
                //->cookie()                                                      // Optional: (parameters: $name,$value)
                //->location()                                                    // Optional: (parameter: $location)
                //->certificate()                                                 // Optional: (parameter: $certLocation)
                //->cache(WSDL_CACHE_NONE)                                        // Optional: Set the WSDL cache
                //->options(['Username' => '', 'Password' => '']);   // Optional: Set some extra options
        });
      
        /*$data = [
         'CurrencyFrom' => 'USD',
         'CurrencyTo'   => 'EUR',
         'RateDate'     => '2014-06-05',
         'Amount'       => '1000'
        ];*/

        SoapWrapper::service('TASASCAMBIO', function ($service){ // use ($data) {
            var_dump($service->getFunctions());
            var_dump($service->call('TASASCAMBIO')->TASASCAMBIOResponse);
        });
    }

> }

**Comment by artisaninweb** [comment]
I think the response on your screen/browser is to much.
Please try it with the example in the documentation.
