### ISSUE TITLE
NTLM Auth

### ISSUE THREAD

**Issue by RockFridrich** [artisaninweb/laravel-soap#67]
Hi!

How to change default SoapClient to my own child class?
I have faced issue with NTLM authentication ([described here](https://jag.gy/php-soapclient-with-ntlm/)).

Just need to implement method setClient()

Thanks in advance!

**Comment by artisaninweb** [comment]
Made this availible in version 0.3.*.
```php
$service->client($customClient)
```

Hope it will help, if you'r having other issues please let me know.
