### ISSUE TITLE
The SOAP action specified on the message, '', does not match the HTTP SOAP Action

### ISSUE THREAD

**Issue by shabeeb** [artisaninweb/laravel-soap#68]
when  i am trying to acces it show some error like this .

SoapFault in Service.php line 218:
                            The SOAP action specified on the message, '', does not match the HTTP SOAP Action, 'http://TekTravel/HotelBookingApi/CountryList'. 
                        

Some can help

**Comment by artisaninweb** [comment]
Does this issue still exists?
If it does, please provide me with more information.

**Comment by shabeeb** [comment]
HI its fixed

**Comment by ReSpawN** [comment]
@shabeeb how'd you fix it? We're running into a similar problem, not necessarily linked to this package.

**Comment by amitlokulwar** [comment]
Hello @shabeeb 
I am also facing same issue. Please give me information how you fixed this issue.
Thank you...
