### ISSUE TITLE
Send a security header

### ISSUE THREAD

**Issue by mledesmac** [artisaninweb/laravel-soap#72]
Hi there

Is a question: 
I need to send through the header something like this:

```
<wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
         <UsernameToken xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
            <Username></Username>
            <Password></Password> 
         </UsernameToken>
     </wsse:Security>
```

How can i do this?
Thanks

**Comment by mledesmac** [comment]
I need to use ->customheader()?

**Comment by artisaninweb** [comment]
If you want to use a custom header you can use the `customHeader()` method.

**Comment by mledesmac** [comment]
Ok. But how can i do this? If the header is security wsse?  I cant find and example or a description to achieve this, using your library.
