### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by mattGoogins** [artisaninweb/laravel-soap#73]
I followed install instructions for Laravel... and when I try and start my server, receive this error message:

Matts-MacBook-Air-2:phpLaravel mattgoogins$ php artisan serve

PHP Fatal error:  Class 'Artisaninweb\SoapWrapper\ServiceProvider' not found in /Users/mattgoogins/GitHub/phpLaravel/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

 [Symfony\Component\Debug\Exception\FatalErrorException]     
  Class 'Artisaninweb\SoapWrapper\ServiceProvider' not found  

Any insight is appreciated.

Thanks!

**Comment by artisaninweb** [comment]
Did you ran the composer install command, before adding the ServiceProvider to Laravel?

**Comment by mattGoogins** [comment]
Also... will this project work with HTTPS-based services I am trying to consumer? When I try and consume HTTPS-based services in native PHP on my MacBook running Sierra, I cannot. Various internet-based sources suggest I may need to install OpenSSL.

**Comment by artisaninweb** [comment]
Yes it should work with HTTPS services.

**Comment by mattGoogins** [comment]
RE: _Did you ran the composer install command, before adding the ServiceProvider to Laravel?_

I don't think so. Can you give me composer install command script example? I'm a newbie (sorry!)

**Comment by artisaninweb** [comment]
In the folder where the composer.json is in, just run the command `composer install`.
This package then will be installed.
Before doing so, first remove the ServiceProvider from the app.php.
After install add it again.
