### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by mattGoogins** [artisaninweb/laravel-soap#74]
I am excited to use this project, and your install instructions were helpful... however, I'm not sure how to apply the usage advice:

Do I create app/Http/Controllers/SoapController.php and place the first code block into that file?

I did create the folder structure you recommended (app/soap, app/soap/request, app/soap/response) and then creates, copied/pasted your code blocks for app/soap/request/GetConversionAmount.php and app/soap/response/GetConversionAmountResponse.php...

How do I actually call the show() method in a blade file?

Any insight is appreciated.

Thank you.

**Comment by artisaninweb** [comment]
I recommend to use my package without the classmap.
You can read the documentation on how to use Laravel here: https://laravel.com/docs/5.3
It wil help you with your other questions.
