### ISSUE TITLE
Classes Not found in 0.3.*

### ISSUE THREAD

**Issue by whfamily2006** [artisaninweb/laravel-soap#76]
I am using this package with Lumen .
Upgrade now on 0.3.1 from 0.2.5.
when i configure aliase for facade it returned with error Class SoapWrapper not found.

`class_alias('Artisaninweb\SoapWrapper\Facades\SoapWrapper', 'SoapWrapper');`

and in previous version i was use SoapService class. which was previously exists in path.

`use Artisaninweb\SoapWrapper\Extension\SoapService;`

now what i use alternate of this class?

**Comment by artisaninweb** [comment]
Try: 
```php class_alias('Artisaninweb\SoapWrapper\SoapWrapper', 'SoapWrapper'); ```
