### ISSUE TITLE
call function some bug!

### ISSUE THREAD

**Issue by maojindao55** [artisaninweb/laravel-soap#78]
```
  public function call($call, $data = [])
  {
    list($name, $function) = explode('.', $call);

    return $this->client($name, function ($client) use ($function, $data) {
      /** @var Client $client */
      return $client->SoapCall($function, $data);
    });
  }
```
need fix to ``return $client->SoapCall($function, array($data));``

as the doc  http://php.net/manual/en/soapclient.soapcall.php

**Comment by artisaninweb** [comment]
As far as i know not all SoapServers need the extra array.
So please add it yourself in the class method.

```php
SoapWrapper::call('function', [['data']]);
```

**Comment by mrodriguez777** [comment]
soap 1.1 & soap 1.2 works different.
a logic fix is change the line :
`return $client->SoapCall($function, $data);`
to
`return` $client->SoapCall($function, ($this->soap_version == 1) ? `[$data]:$data);`

**Comment by meirtin** [comment]
soap 1.1 & soap 1.2 works different.
a logic fix is change the line :

return $client->SoapCall($function, $data);
to
return $client->SoapCall($function, ($this->soap_version == 1) ? [$data]:$data);

**Comment by maojindao55** [comment]
@meirtin ok
