### ISSUE TITLE
Eror Installing

### ISSUE THREAD

**Issue by rizdian** [artisaninweb/laravel-soap#80]
![capture](https://cloud.githubusercontent.com/assets/23713183/22092859/99be73f8-de33-11e6-8ed5-bbfc22d32815.PNG)

Eror Composer Install and Composer Update .

How to fix it?

Thanks

**Comment by angelinux** [comment]
You have to install php soap extension http://stackoverflow.com/questions/2509143/php-how-do-i-install-soap-extension
