### ISSUE TITLE
Passing a multidimensional array through the call() method?

### ISSUE THREAD

**Issue by f7n** [artisaninweb/laravel-soap#82]
My SOAP request structure needs to look something along these lines:

	<soapenv:Envelope>
	   <soapenv:Header/>
	   <soapenv:Body>
	      <v2:startFunction>
	         <v2:Type></v2:Type>
	         <v2:Session>?</v2:Session>
	         <v2:People>
	         	<Employee>
	         		<name></name>
	         	</Employee>
	         </v2:People>
	      </v2:startFunction>
	   </soapenv:Body>
	</soapenv:Envelope>

I'm trying to pass these values as the second parameter of the `call()` method as an array:

    $data = ['type' => 'foo', 'session' => 'foobar', 'People' => ['Employee' => ['name' => 'John']]];
    $result = $service->call('startFunction', [$data]);

Is this the correct way to pass a multidimensional array using the call() method?

**Comment by artisaninweb** [comment]
Yes this is a good way to pass a multidimensional array.
