### ISSUE TITLE
SoapFault exception: [HTTP] Internal Server 

### ISSUE THREAD

**Issue by rommelquiddity** [artisaninweb/laravel-soap#84]
What was the cause of this problem? Help me please thanks

SoapFault exception: [HTTP] Internal Server Error in /opt/altengine/vendor/artisaninweb/laravel-soap/src/Artisaninweb/SoapWrapper/Service.php:218 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://192.168....', 'urn:TESTWSDL#su...', 1, 0) #1 [internal function]: SoapClient->__call('submitApplicati...', Array) #2 /opt/altengine/vendor/artisaninweb/laravel-soap/src/Artisaninweb/SoapWrapper/Service.php(218): call_user_func_array(Array, Array) #3 /opt/altengine/app/Http/Controllers/TESTApi.php(65): Artisaninweb\SoapWrapper\Service-

**Comment by artisaninweb** [comment]
Most of the time if you get a Internal Server Error it has something to do with your htaccess.
That's my experience, can you open the WSDL in a browser?

**Comment by rommelquiddity** [comment]
Yes, this error happened not all the time. is this server picky timeout issue?

**Comment by artisaninweb** [comment]
Not sure, don't think the issue is in this package.
