### ISSUE TITLE
Getting error in laravel 5.2

### ISSUE THREAD

**Issue by ankitparmar372** [artisaninweb/laravel-soap#91]
Call to a member function add() on null...
pls help me to solve out. thanks

**Comment by artisaninweb** [comment]
Can you send me the code please?

**Comment by ankitparmar372** [comment]
can give me your email id or skype so i send you my code?

**Comment by ankitparmar372** [comment]
i have implemt below api and this is its documentation and error screen shot.
https://drive.google.com/open?id=0By2oFa3ihKgCQ2VTaHZOOWh3SEk

**Comment by artisaninweb** [comment]
First you need to add a name to your service:
`$this->soapWrapper->add('ServiceName', function(){});`.

Then you need to call the function on that service
`$this->soapWrapper->add('ServiceName.FunctionName',[]);`.

Check you WSDL URL as well.
