### ISSUE TITLE
Responses either -1 or 0

### ISSUE THREAD

**Issue by emperorjm** [artisaninweb/laravel-soap#92]
I don't know what is the issue but when I try your example I get back a string "0" and when I try a service that returns a float I get -1. I have looked through almost all the issues posted and saw one or two older issues with the similar problem and tried the solution but still getting the same responses.

My code is as follows:

`$soapWrapper = new SoapWrapper;

            /**$soapWrapper->add('Currency', function ($service) {
                $service->wsdl('http://currencyconverter.kowabunga.net/converter.asmx?WSDL')
                    ->trace(true);
            });

            $response = $soapWrapper->call('Currency.GetConversionAmount', [
                'CurrencyFrom' => 'USD', 
                'CurrencyTo'   => 'EUR', 
                'RateDate'     => '2014-06-05', 
                'Amount'       => '1000',
            ]);**/

            $request = $soapWrapper->add('test1', function ($service) {
                $service->wsdl('http://www.webservicex.net/CurrencyConvertor.asmx?WSDL');
            });

            $response = $soapWrapper->call('test1.ConversionRate', [
                'FromCurrency' => 'JMD',
                'ToCurrency' => 'EUR'
            ]);

            var_dump($response);`

The result I get is:

object(stdClass)#2031 (1) {
	["ConversionRateresult"] => float(-1)
}

**Comment by artisaninweb** [comment]
Check your paramaters:
```
[
  'FromCurrency' => 'JMD',
  'ToCurrency' => 'EUR'
]
```
In my example it says `CurrencyFrom` you have `FromCurrency`.
Same for `ToCurrency`.

**Comment by emperorjm** [comment]
Your example is commented out above in the code. I am using another SOAP service from http://www.webservicex.net/CurrencyConvertor.asmx?WSDL
