### ISSUE TITLE
Is trace working ?

### ISSUE THREAD

**Issue by sebnyc** [artisaninweb/laravel-soap#94]
I would like to monitor and troubleshoot my requests, maybe the `$service->trace(true)` could help.
Does it actually work ? Where can I see the traces ?

**Comment by edwardsteven** [comment]
use $service->getLastRequest(); trace stores the last request and you can access it using this.

**Comment by cdarken** [comment]
@edwardsteven How exactly would I call that? How do I get the $service object?

**Comment by edwardsteven** [comment]
@cdarken right, getLastRequest belongs to SoapClient. My apologies, my answer wasn't clear - I extend the Client class which gives me direct access to this method, however the Service class has a getClient method, so you could call $service->getClient()->getLastRequest().

**Comment by cdarken** [comment]
Yeah, I managed to debug it in the end. Thanks.

**Comment by sebnyc** [comment]
@cdarken Could you share your code ? I can't make it work
