### ISSUE TITLE
[MessageId=unknown]  Bad request.

### ISSUE THREAD

**Issue by Neve12ende12** [artisaninweb/laravel-soap#95]
The following code works.  However, when I try to convert is using this service provided, I get [MessageId=unknown]  Bad request.  What am I doing wrong?

    $client = new \SoapClient('http://test:25400/v2/account?wsdl'); 
            
            
            $response = $client->createAccount(array(
                'Request' => array(
                    'MessageId' => '1', 
                    'AccountCreatableFields' => ['Type' => '0'],
                    'NameCreatableFields' => ['Type' => '0'],
                    'Credentials' => array(
                        'AdministrativeCredentials' => array(
                           'Password' => '*****',
                        ),
                    ),
                    'DeviceInformation' => array(
                        'DeviceType' => TEST,
                        'DeviceNumber' => '20207'
                    )
                )
            ));

This doesn't work

    $this->soap->add('account', function ($service) {
                $service->wsdl('http://test:25400/v2/account?wsdl')->trace(true);
            });
            
            $response = $this->soap->call('account.createAccount', [
                'Request' => [
                    'MessageId' => '1', 
                    'AccountCreatableFields' => [
                        'Type' => '0'
                    ],
                    'NameCreatableFields' => [
                        'Type' => '0'
                    ],
                    'Credentials' => array(
                        'AdministrativeCredentials' => [
                           'Password' => '*****',
                        ],
                    ),
                    'DeviceInformation' => [
                        'DeviceType' => 'TEST',
                        'DeviceNumber' => '20207'
                    ]
                ]
            ]);

**Comment by artisaninweb** [comment]
Can you please try version 0.3.0.5 think this may solve your problem.
