### ISSUE TITLE
send sessionId with calls

### ISSUE THREAD

**Issue by nickbr5** [artisaninweb/laravel-soap#96]
Hi guys,

I'm having some issues with staying authenticated when performing calls with this package.
I have one call to a function with username & password and this returns me a sessionId.
How do i send this sessionId with the next calls?

ps: i used this package before in Lumen, and i didn't had this issue somehow.

**Comment by nickbr5** [comment]
found it!
It had to do with this issue: #79

**Comment by artisaninweb** [comment]
@nickbr5 i fixed the bug in version 0.3.0.5, can you please test if this solves your problem?

**Comment by nickbr5** [comment]
@artisaninweb Did something else change in this update?
Now i get errors from the login call:
System.NullReferenceException: Object reference not set to an instance of an object.\n

**Comment by artisaninweb** [comment]
Can you please try version: 0.3.0.6

**Comment by artisaninweb** [comment]
No reaction, if you still have this problem please let me know.
Closing for now.
